version: '2.4'

services:
  web_wallet:
    build:
      context: .
      dockerfile: ./Applications/WebApp/Dockerfile
    image: webwallet/wallet_webapp:0.1
    container_name: wallet_webapp
    hostname: wallet_webapp
    ports: 
      - "8020:80"
    depends_on: 
      mssql:
        condition: service_healthy       
    networks: 
      - wallet_network

  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: wallet_mssql
    hostname: wallet_mssql
    ports:
      - "1433:1433"
    environment: 
      SA_PASSWORD: "Krusevac037"
      ACCEPT_EULA: "Y"
    volumes: 
      - "mssqldata:/var/lib/mssql"
    networks: 
      - wallet_network

    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-U", "sa", "-P", "Krusevac037"]
      interval: 20s
      timeout: 10s
      start_period: 5s
      retries: 5


volumes: 
  mssqldata:
networks: 
  wallet_network: